### ISSUE TITLE
Will this supports android and ios?

### ISSUE THREAD

**Issue by Dorbmon** [Ahmadre/image_picker_web#1]

**Comment by Ahmadre** [comment]
Nope. Not this repo. There're just an image_picker for mobile: https://pub.dev/packages/image_picker

**Comment by Dorbmon** [comment]
But it doesn't support web.

**Comment by Ahmadre** [comment]
Of course It's not. Because It's mobile. It's maintained by the Google Team. They built a platform_interface for url_launcher for example, where it's both mobile and web. But till now, there're no platform_interface for image_picker. You've to file an issue on Google's Package site: https://github.com/flutter/plugins

**Comment by Dorbmon** [comment]
Thank you very much.
