### ISSUE TITLE
Not Working On Android

### ISSUE THREAD

**Issue by NihatCelik** [Ahmadre/image_picker_web#28]
I installed the package in my project but the packet worked on the web but didn't work on android. I couldn't run the project.

**Comment by TesteurManiak** [comment]
This package is dedicated to the web version of flutter only. You will need to make your own implementation to use it on Android, iOS or any other target than Flutter for Web. If you encounter some kind of issue it might be because you are executing or importing this package on a platform other than web.

Consider separating your methods for image picking by using conditional imports.

## Example

If you consider having your image picking methods in separate files it would look like something like this:

```dart
import 'image_picker_implementation_default.dart'
    if (dart.library.io) 'image_picker_implementation_mobile.dart'
    if (dart.library.js) 'image_picker_implementation_web.dart';
```

If you need further informations please provide a minimal reproducible example of your code.
